language: java

jdk:
- oraclejdk7

install: ''

script: mvn clean install deploy --settings src/main/config/travis-maven-settings.xml -U

env:
  global:
  - secure: gmpxRh1l6+0oZXdgLJSxwINbUgb94YH2S8ODhu103LXpvNJvjFe5taiWKvWLeCWiuOzgy/a1YcBpPv2dBMESC1iOLNxkGshSIP/tZzi7kxKpkdCKbo6bdWKSWzJCuiTIGQCqSF+QwGwS8NVwLIgacvSQSNcCZTYBTNYIkSDCZaQ=
  - secure: MjjkHmm1DlvwZJoPq28Pt1hTr4tMSQDLeejMzancp68iJM/cnNNQmyAuk8J6pGgvduRrLSHM1b9zird8Lv7EdblwsXl/LCnQgHRZNGvLMsT2BSotXua+KcwzWNzZdPvByqEWR9uvwobEHjAP4u8ZXu5TiFxnyiDmih3+zq18MmI=
