language: java

jdk:
- oraclejdk7

script: mvn clean install deploy --settings src/main/config/travis-maven-settings.xml

env:
  global:
  - secure: H1j/RStGsb2gtnKvXo1CLPX4EvQeBuwT5GwHVjMSiZiAt5BifulSvyLBX0OPVg/Jb6f4/KSF44KTvzsj2jCkk6ma32SAU7icrd/Zr1EkfZUydfKTog3e03NVNg/wD+8QcVR209nwo1BzCRhqut+dERPCfSdPYk/WgnGZ5xk/WJo=
  - secure: d1ZjkpmbiHYJN2uyCHIkfvthFeGdY24TZvkf/UFm1ZoH5vctuuQZHtfPDYlRUcsoxLgyF0jpeOWX248SLDSSLA/f9FdndDrHZkgHhQh1bf7Cmdo1C/zUSY1rBlifj4SEHxPrOh6JbKLSECdtzQt6JrDiVbUFhfXDN3xL4qin72U=
