language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
env:
  global:
  - secure: IkU9pjt3AkMlMqu8jIP0Gxd4Hgi//ITiDSzvqRPHdoQIJmLgf6XEuSU+c/NHEmF3LhSgS167wZLWC7x5vFA9hjuzgugu0GRR3QwhOTurerWCT/0cYPuijAlYVWgGkHC/Sw3vZSnIz3iyhodD242z8f+cjJmaZQQRVh854idjHOM=
  - secure: d3iKvwB6U//xWWsdg/mKFZaLhEp85VI9ic9d0BFCjyS350SQcmKE8FMxdbfBQix++UZ+BoJ8Hm1MeMMjjEreOtPXEVWd754SkzxR8h76XYqsMOAhZfPRiPTTWzvx3qRgSls3rdhcYYNcwKPYmFR5Gb1fHpLgec9fbkHUhgblWjs=
